Repository TeamViewMore/Poksin_BE, pull requests merged in 2024-08, with the labels that each got.

#44 📝[DOCS] 채팅 API 문서화
  src/main/java/com/viewmore/poksin/controller/ChatAPI.java
Labels: :memo: Docs

#57 🐛[FIX] 채팅방 생성 시 인증 추가
  src/main/java/com/viewmore/poksin/config/WebSocketConfig.java
  src/main/java/com/viewmore/poksin/controller/ChatAPI.java
  src/main/java/com/viewmore/poksin/controller/ChatController.java
Labels: :bug: Fix

#65 ✨[FEAT] mypage에 마지막 채팅 조회 추가
  src/main/java/com/viewmore/poksin/dto/user/UserResponseDTO.java
  src/main/java/com/viewmore/poksin/repository/ChatMessageRepository.java
  src/main/java/com/viewmore/poksin/service/UserService.java
Labels: :sparkles: Feat

#67 ♻️[REFACTOR] 채팅 파일 업로드 sender 개선
  src/main/java/com/viewmore/poksin/controller/ChatController.java
  src/main/java/com/viewmore/poksin/service/ChatService.java
Labels: :recycle: Refactor

#75 [FEAT] 상담사 마이페이지 수정
  src/main/java/com/viewmore/poksin/dto/user/CounselorResponseDTO.java
  src/main/java/com/viewmore/poksin/entity/CounselorEntity.java
  src/main/java/com/viewmore/poksin/repository/ChatMessageRepository.java
  src/main/java/com/viewmore/poksin/service/CounselorService.java
Labels: :sparkles: Feat

#81 [FIX] ãjava 버ì 전 변경
  build.gradle
Labels: :bug: Fix

#84 [FIX] 채팅 파일 시간 수정
  src/main/java/com/viewmore/poksin/service/ChatService.java
Labels: :bug: Fix

#88 [FIX] 채팅방 생성 로직 수정
  src/main/java/com/viewmore/poksin/controller/ChatController.java
  src/main/java/com/viewmore/poksin/repository/EvidenceRepository.java
  src/main/java/com/viewmore/poksin/service/ChatService.java
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
Labels: :bug: Fix
