Repository TeamViewMore/Poksin_BE, pull requests merged in 2024-07, with the labels that each got.

#2 ✨ [FEAT] 회원가입
  .gitignore
  build.gradle
  src/main/java/com/viewmore/poksin/PoksinApplication.java
  src/main/java/com/viewmore/poksin/code/ErrorCode.java
  src/main/java/com/viewmore/poksin/code/SuccessCode.java
  src/main/java/com/viewmore/poksin/config/SecurityConfig.java
  src/main/java/com/viewmore/poksin/controller/UserController.java
  src/main/java/com/viewmore/poksin/dto/RegisterDTO.java
  src/main/java/com/viewmore/poksin/entity/BaseEntity.java
  src/main/java/com/viewmore/poksin/entity/UserEntity.java
  src/main/java/com/viewmore/poksin/exception/DuplicateUsernameException.java
  src/main/java/com/viewmore/poksin/exception/GlobalHandleException.java
  src/main/java/com/viewmore/poksin/repository/UserRepository.java
  src/main/java/com/viewmore/poksin/response/ErrorResponseDTO.java
  src/main/java/com/viewmore/poksin/response/ResponseDTO.java
  src/main/java/com/viewmore/poksin/service/UserService.java
  src/main/resources/application.yml
Labels: :bug: Fix, 🛠️ Chore, :sparkles: Feat

#8 ✨[FEAT] 증거 업로드 및 삭제
  build.gradle
  src/main/java/com/viewmore/poksin/code/ErrorCode.java
  src/main/java/com/viewmore/poksin/code/SuccessCode.java
  src/main/java/com/viewmore/poksin/config/CorsConfig.java
  src/main/java/com/viewmore/poksin/config/S3Config.java
  src/main/java/com/viewmore/poksin/controller/EvidenceController.java
  src/main/java/com/viewmore/poksin/dto/evidence/CreateEvidenceDTO.java
  src/main/java/com/viewmore/poksin/dto/evidence/EvidenceResponseDTO.java
  src/main/java/com/viewmore/poksin/entity/CategoryEntity.java
  src/main/java/com/viewmore/poksin/entity/CategoryTypeEnum.java
  src/main/java/com/viewmore/poksin/entity/EvidenceEntity.java
  src/main/java/com/viewmore/poksin/entity/UserEntity.java
  src/main/java/com/viewmore/poksin/exception/CategoryNotFoundException.java
  src/main/java/com/viewmore/poksin/exception/EvidenceNotFoundException.java
  src/main/java/com/viewmore/poksin/exception/GlobalHandleException.java
  src/main/java/com/viewmore/poksin/repository/CategoryRepository.java
  src/main/java/com/viewmore/poksin/repository/EvidenceRepository.java
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
  src/main/java/com/viewmore/poksin/service/S3Uploader.java
  src/main/resources/import.sql
Labels: 🛠️ Chore, :recycle: Refactor, :sparkles: Feat

#15 "[FEAT] fast api에 요청하기 및 violence_segment 엔티티 생성 #12"
  src/main/java/com/viewmore/poksin/code/ErrorCode.java
  src/main/java/com/viewmore/poksin/config/RestTemplateConfig.java
  src/main/java/com/viewmore/poksin/entity/ViolenceSegmentEntity.java
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
  src/main/java/com/viewmore/poksin/service/S3Uploader.java
Labels: :recycle: Refactor, :sparkles: Feat

#25 ✨[FEAT] 채팅방 1차 구현
  build.gradle
  src/main/java/com/viewmore/poksin/PoksinApplication.java
  src/main/java/com/viewmore/poksin/code/SuccessCode.java
  src/main/java/com/viewmore/poksin/config/SecurityConfig.java
  src/main/java/com/viewmore/poksin/config/WebConfig.java
  src/main/java/com/viewmore/poksin/config/WebSocketConfig.java
  src/main/java/com/viewmore/poksin/controller/ChatController.java
  src/main/java/com/viewmore/poksin/controller/UserController.java
  src/main/java/com/viewmore/poksin/dto/chat/ChatRoomDTO.java
  src/main/java/com/viewmore/poksin/dto/user/UserResponseDTO.java
  src/main/java/com/viewmore/poksin/entity/ChatMessageEntity.java
  src/main/java/com/viewmore/poksin/entity/ChatRoomEntity.java
  src/main/java/com/viewmore/poksin/handler/ChatWebSocketHandler.java
  src/main/java/com/viewmore/poksin/jwt/LoginFilter.java
  src/main/java/com/viewmore/poksin/repository/ChatMessageRepository.java
  src/main/java/com/viewmore/poksin/repository/ChatRoomRepository.java
  src/main/java/com/viewmore/poksin/service/ChatService.java
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
  src/main/java/com/viewmore/poksin/service/SessionManager.java
  src/main/java/com/viewmore/poksin/service/UserService.java
Labels: :sparkles: Feat

#26 [FEAT] 검출한 영상 조회, detection에 폭력 검출 내용 작성
  src/main/java/com/viewmore/poksin/code/SuccessCode.java
  src/main/java/com/viewmore/poksin/controller/EvidenceController.java
  src/main/java/com/viewmore/poksin/dto/evidence/EvidenceDetailResponseDTO.java
  src/main/java/com/viewmore/poksin/entity/EvidenceEntity.java
  src/main/java/com/viewmore/poksin/exception/ViolenceSegmentNotFoundException.java
  src/main/java/com/viewmore/poksin/repository/ViolenceSegmentRepository.java
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
  src/main/java/com/viewmore/poksin/service/S3Uploader.java
Labels: :sparkles: Feat

#27 [FIX] 충돌 해결
  src/main/java/com/viewmore/poksin/service/EvidenceService.java
Labels: :bug: Fix

#30 ✨[FEAT] 채팅 상담사 차단, 파일 업로드 기능 구현
  src/main/java/com/viewmore/poksin/code/ErrorCode.java
  src/main/java/com/viewmore/poksin/code/SuccessCode.java
  src/main/java/com/viewmore/poksin/controller/ChatController.java
  src/main/java/com/viewmore/poksin/entity/ChatMessageEntity.java
  src/main/java/com/viewmore/poksin/entity/ChatRoomEntity.java
  src/main/java/com/viewmore/poksin/service/ChatService.java
Labels: :sparkles: Feat

#37 ✨[FEAT] 채팅 실시간 처리 수정
  .github/workflows/develop.yml
  Dockerfile
  src/main/java/com/viewmore/poksin/controller/ChatController.java
  src/main/java/com/viewmore/poksin/entity/ChatMessageEntity.java
  src/main/java/com/viewmore/poksin/handler/ChatWebSocketHandler.java
  src/main/java/com/viewmore/poksin/service/ChatService.java
Labels: :sparkles: Feat
